packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  better-auth: 1.4.0-beta.9
  "@better-auth/expo": 1.4.0-beta.9
  "@better-auth/cli": 1.4.0-beta.9
  tailwindcss: ^4.1.14
  "@tailwindcss/postcss": ^4.1.14
  typescript: ^5.9.3
  zod: ^4.1.12
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.6.0
  "@trpc/server": ^11.6.0
  "@trpc/tanstack-react-query": ^11.6.0
  "@t3-oss/env-nextjs": ^0.13.6

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
