packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.9
  '@better-auth/expo': 1.4.9
  '@t3-oss/env-core': ^0.13.10
  '@t3-oss/env-nextjs': ^0.13.10
  '@tailwindcss/postcss': ^4.1.18
  '@tanstack/react-query': ^5.90.12
  '@trpc/client': ^11.8.1
  '@trpc/server': ^11.8.1
  '@trpc/tanstack-react-query': ^11.8.1
  better-auth: 1.4.9
  next: ^16.1.1
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  zod: ^4.2.1

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
