packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.20
  '@better-auth/expo': 1.4.20
  '@t3-oss/env-core': ^0.13.10
  '@t3-oss/env-nextjs': ^0.13.10
  '@tailwindcss/postcss': ^4.2.1
  '@tanstack/react-query': ^5.90.21
  '@trpc/client': ^11.10.0
  '@trpc/server': ^11.10.0
  '@trpc/tanstack-react-query': ^11.10.0
  better-auth: 1.4.20
  next: ^16.1.6
  tailwindcss: ^4.2.1
  typescript: ^5.9.3
  zod: 4.3.6

catalogs:
  react19:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
