packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.0-beta.9
  '@better-auth/expo': 1.4.0-beta.9
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@tailwindcss/postcss': ^4.1.17
  '@tanstack/react-query': ^5.90.11
  '@trpc/client': ^11.7.2
  '@trpc/server': ^11.7.2
  '@trpc/tanstack-react-query': ^11.7.2
  better-auth: 1.4.0-beta.9
  next: ^16.0.5
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  zod: ^4.1.13

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: 19.1.1
    react-dom: 19.1.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
